lokiServiceAccountSecretName: "k8s-minio-service-account-loki"
global:
  networkPolicies:
    enabled: true
  imagePullSecrets:
    - "ces-container-registries"
upgradeContainer:
  kubectl:
    image:
      registry: "docker.io"
      repository: "bitnami/kubectl"
      tag: "1.33.1"
minio:
  networkPolicy:
    enabled: false
  resources:
    limits:
      memory: 300M
    requests:
      cpu: 100m
      memory: 300M
  commonLabels:
    app: ces
    app.kubernetes.io/name: k8s-minio
  console:
    enabled: false
  auth:
    existingSecret: "k8s-minio-root-user"
  provisioning:
    enabled: true
    resources:
      limits:
        memory: 249M
      requests:
        cpu: 100m
        memory: 249M
    networkPolicy:
      enabled: false
    usersExistingSecrets: ["k8s-minio-service-account-provisioning"]
    buckets:
      - name: "loki-log-bucket"
        versioning: false
# serviceAccount is only needed for the minio secret. We don't create the minio secret,
# because we define our own auth secret in minio.auth.existingSecret. Thus, it can be deactivated.
  serviceAccount:
    create: false
  automountServiceAccountToken: false
