lokiServiceAccountSecretName: "k8s-minio-service-account-loki"
global:
  imagePullSecrets:
    - "ces-container-registries"
minio:
  commonLabels:
    app: ces
    app.kubernetes.io/name: k8s-minio
  auth:
    existingSecret: "k8s-minio-root-user"
  provisioning:
    enabled: true
    usersExistingSecrets: ["k8s-minio-service-account-provisioning"]
    buckets:
      - name: "loki-log-bucket"
        versioning: false
# serviceAccount is only needed for the minio secret. We don't create the minio secret,
# because we define our own auth secret in minio.auth.existingSecret. Thus, it can be deactivated.
  serviceAccount:
    automountServiceAccountToken: false
