{{- if .Values.global.networkPolicies.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ printf "%s-deny-ingress" (include "common.names.fullname" .) | trunc 63 | trimSuffix "-" }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.minio.commonLabels "context" $ ) | nindent 4 }}
  {{- if .Values.minio.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.minio.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  podSelector:
    matchLabels:
      {{- toYaml .Values.minio.commonLabels | nindent 6 }}
  policyTypes:
    - Ingress
{{- end }}