{{ $username := "loki-serviceaccount" }}
{{ $password :=  randAlphaNum 24  }}

# this secret is used by minio for provisioning the user
apiVersion: v1
kind: Secret
metadata:
  name: k8s-minio-service-account-provisioning
  labels:
    app: ces
    app.kubernetes.io/name: k8s-minio
type: Opaque
stringData:
  lokiserviceaccount: |
    username={{ $username }}
    password={{ $password }}
    disabled=false
    policies=readwrite
    setPolicies=true
---
# this secret is used by loki for accessing minio
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.lokiServiceAccountSecretName }}
  labels:
    app: ces
    app.kubernetes.io/name: k8s-minio
type: Opaque
data:
  accessKeyId: {{ $username | b64enc }}
  accessKeySecret: {{ $password | b64enc }}