# This job has been created to allow the upgrade from <17 to >=17.
# The deployment has modified immutable fields and without removing the deployment before upgrade,
# the upgrade won't work.
apiVersion: batch/v1
kind: Job
metadata:
  name: k8s-minio-pre-upgrade
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded
    "helm.sh/hook-weight": "0"
spec:
  template:
    spec:
      serviceAccountName: hook-sa
      restartPolicy: Never
      containers:
        - name: deleter
          image: bitnami/kubectl:latest
          command:
            - /bin/sh
            - -c
            - |
              echo "Deleting existing deployment..."
              kubectl delete deployment k8s-minio --namespace {{ .Release.Namespace }} || true
              kubectl scale statefulset k8s-loki-write --replicas=0 -n {{ .Release.Namespace }} || true
              kubectl scale statefulset k8s-loki-backend --replicas=0 -n {{ .Release.Namespace }}
              kubectl scale deployment k8s-loki-read --replicas=0 -n {{ .Release.Namespace }}
              kubectl scale deployment k8s-loki-gateway --replicas=0 -n {{ .Release.Namespace }}
