apiVersion: v1
kind: Secret
metadata:
  name: k8s-minio-root-user
  labels:
    app: ces
    app.kubernetes.io/name: k8s-minio
type: Opaque
data:
  root-user: {{ "admin" | b64enc }}
  root-password: {{ randAlphaNum 24 | b64enc }}